#!/bin/bash
# YOLOv8 Training Pipeline - Quick Start Guide

echo "======================================================================"
echo "YOLOv8 Training Pipeline - Combined Dataset (COCO + FOD + Mech Tools)"
echo "======================================================================"
echo ""
echo "Virtual Environment: venv (already created)"
echo "GPU: NVIDIA GeForce RTX 4070 Laptop GPU"
echo "Total Classes: 86 (80 COCO + 6 custom)"
echo ""
echo "======================================================================"
echo "WORKFLOW:"
echo "======================================================================"
echo ""
echo "Step 1: Merge datasets"
echo "  Run: source venv/bin/activate && python merge_datasets.py"
echo "  This will:"
echo "  - Copy FOD dataset (class 0 → 80)"
echo "  - Copy Mechanical Tools (classes 0-4 → 81-85)"
echo "  - Optionally merge with COCO (classes 0-79)"
echo "  - Output: datasets/combined/"
echo ""
echo "Step 2: Train the model"
echo "  Run: source venv/bin/activate && python train.py"
echo "  This will:"
echo "  - Load pretrained yolov8s.pt"
echo "  - Train on combined dataset (20 epochs)"
echo "  - Use GPU acceleration"
echo "  - Save results to runs/detect/combined_yolo/"
echo ""
echo "Step 3: Run inference"
echo "  Run: source venv/bin/activate && python inference.py --source <image/folder/video>"
echo "  Example: python inference.py --source test.jpg --save --show"
echo "  Options:"
echo "    --source: Path to image, folder, or video"
echo "    --model: Path to trained model (default: best.pt)"
echo "    --conf: Confidence threshold (default: 0.25)"
echo "    --save: Save detection results"
echo "    --show: Display detection results"
echo ""
echo "======================================================================"
echo "CLASS MAPPING:"
echo "======================================================================"
echo "COCO classes: 0-79 (person, car, dog, etc.)"
echo "Custom classes:"
echo "  80: FOD (Foreign Object Debris)"
echo "  81: drill"
echo "  82: hammer"
echo "  83: pliers"
echo "  84: screwdriver"
echo "  85: wrench"
echo ""
echo "======================================================================"
echo "FILES CREATED:"
echo "======================================================================"
echo "  merge_datasets.py    - Merge COCO + custom datasets with remapping"
echo "  combined_data.yaml   - Dataset config (86 classes)"
echo "  train.py             - Training script"
echo "  inference.py         - Inference script"
echo "  download_coco.py     - COCO download helper (optional)"
echo ""
echo "======================================================================"
echo "QUICK START:"
echo "======================================================================"
echo ""
echo "1. Activate venv:"
echo "   source venv/bin/activate"
echo ""
echo "2. Merge datasets (without COCO for faster start):"
echo "   python merge_datasets.py"
echo ""
echo "3. Train (this will take a while):"
echo "   python train.py"
echo ""
echo "4. Test inference:"
echo "   python inference.py --source test_image.jpg --save"
echo ""
echo "======================================================================"
